package cn.zg.dao.inter;

import cn.zg.entity.daoEntity.ComponentsType;
import java.util.List;

public interface ComponentsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String ctyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_type
     *
     * @mbg.generated
     */
    int insert(ComponentsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_type
     *
     * @mbg.generated
     */
    ComponentsType selectByPrimaryKey(String ctyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_type
     *
     * @mbg.generated
     */
    List<ComponentsType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComponentsType record);
}