package cn.zg.dao.inter;

import cn.zg.entity.daoEntity.ComponentsInstance;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ComponentsInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_instance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String ciid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_instance
     *
     * @mbg.generated
     */
    int insert(ComponentsInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_instance
     *
     * @mbg.generated
     */
    ComponentsInstance selectByPrimaryKey(String ciid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_instance
     *
     * @mbg.generated
     */
    List<ComponentsInstance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_instance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComponentsInstance record);
}