package cn.zg.dao.inter;

import cn.zg.entity.daoEntity.ComponentsTemplate;
import java.util.List;

public interface ComponentsTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_template
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String ctid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_template
     *
     * @mbg.generated
     */
    int insert(ComponentsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_template
     *
     * @mbg.generated
     */
    ComponentsTemplate selectByPrimaryKey(String ctid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_template
     *
     * @mbg.generated
     */
    List<ComponentsTemplate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComponentsTemplate record);
}