package cn.zg.dao.inter;

import cn.zg.entity.daoEntity.LayoutTemplate;
import java.util.List;

public interface LayoutTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table layout_template
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String tiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table layout_template
     *
     * @mbg.generated
     */
    int insert(LayoutTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table layout_template
     *
     * @mbg.generated
     */
    LayoutTemplate selectByPrimaryKey(String tiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table layout_template
     *
     * @mbg.generated
     */
    List<LayoutTemplate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table layout_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LayoutTemplate record);
}