package cn.zg.entity.daoEntity;

import java.io.Serializable;

public class ComponentsType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column components_type.ctyid
     *
     * @mbg.generated
     */
    private String ctyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column components_type.components_type_name
     *
     * @mbg.generated
     */
    private String componentsTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table components_type
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column components_type.ctyid
     *
     * @return the value of components_type.ctyid
     *
     * @mbg.generated
     */
    public String getCtyid() {
        return ctyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column components_type.ctyid
     *
     * @param ctyid the value for components_type.ctyid
     *
     * @mbg.generated
     */
    public void setCtyid(String ctyid) {
        this.ctyid = ctyid == null ? null : ctyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column components_type.components_type_name
     *
     * @return the value of components_type.components_type_name
     *
     * @mbg.generated
     */
    public String getComponentsTypeName() {
        return componentsTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column components_type.components_type_name
     *
     * @param componentsTypeName the value for components_type.components_type_name
     *
     * @mbg.generated
     */
    public void setComponentsTypeName(String componentsTypeName) {
        this.componentsTypeName = componentsTypeName == null ? null : componentsTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_type
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ctyid=").append(ctyid);
        sb.append(", componentsTypeName=").append(componentsTypeName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}