package cn.zg.entity.daoEntity;

import java.io.Serializable;

public class ComponentsInstance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column components_instance.ciid
     *
     * @mbg.generatedc
     */
    private String ciid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column components_instance.components_instance_name
     *
     * @mbg.generated
     */
    private String componentsInstanceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column components_instance.components_instance_url
     *
     * @mbg.generated
     */
    private String componentsInstanceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column components_instance.ctid
     *
     * @mbg.generated
     */
    private String ctid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column components_instance.liid
     *
     * @mbg.generated
     */
    private String liid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table components_instance
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column components_instance.ciid
     *
     * @return the value of components_instance.ciid
     *
     * @mbg.generated
     */
    public String getCiid() {
        return ciid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column components_instance.ciid
     *
     * @param ciid the value for components_instance.ciid
     *
     * @mbg.generated
     */
    public void setCiid(String ciid) {
        this.ciid = ciid == null ? null : ciid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column components_instance.components_instance_name
     *
     * @return the value of components_instance.components_instance_name
     *
     * @mbg.generated
     */
    public String getComponentsInstanceName() {
        return componentsInstanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column components_instance.components_instance_name
     *
     * @param componentsInstanceName the value for components_instance.components_instance_name
     *
     * @mbg.generated
     */
    public void setComponentsInstanceName(String componentsInstanceName) {
        this.componentsInstanceName = componentsInstanceName == null ? null : componentsInstanceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column components_instance.components_instance_url
     *
     * @return the value of components_instance.components_instance_url
     *
     * @mbg.generated
     */
    public String getComponentsInstanceUrl() {
        return componentsInstanceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column components_instance.components_instance_url
     *
     * @param componentsInstanceUrl the value for components_instance.components_instance_url
     *
     * @mbg.generated
     */
    public void setComponentsInstanceUrl(String componentsInstanceUrl) {
        this.componentsInstanceUrl = componentsInstanceUrl == null ? null : componentsInstanceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column components_instance.ctid
     *
     * @return the value of components_instance.ctid
     *
     * @mbg.generated
     */
    public String getCtid() {
        return ctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column components_instance.ctid
     *
     * @param ctid the value for components_instance.ctid
     *
     * @mbg.generated
     */
    public void setCtid(String ctid) {
        this.ctid = ctid == null ? null : ctid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column components_instance.liid
     *
     * @return the value of components_instance.liid
     *
     * @mbg.generated
     */
    public String getLiid() {
        return liid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column components_instance.liid
     *
     * @param liid the value for components_instance.liid
     *
     * @mbg.generated
     */
    public void setLiid(String liid) {
        this.liid = liid == null ? null : liid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_instance
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ciid=").append(ciid);
        sb.append(", componentsInstanceName=").append(componentsInstanceName);
        sb.append(", componentsInstanceUrl=").append(componentsInstanceUrl);
        sb.append(", ctid=").append(ctid);
        sb.append(", liid=").append(liid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}