package cn.zg.entity.daoEntity;

import java.io.Serializable;

public class ComponentsTemplate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column components_template.ctid
     *
     * @mbg.generated
     */
    private String ctid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column components_template.ctyid
     *
     * @mbg.generated
     */
    private String ctyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column components_template.components_template_name
     *
     * @mbg.generated
     */
    private String componentsTemplateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column components_template.components_template_person
     *
     * @mbg.generated
     */
    private String componentsTemplatePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column components_template.components_template_url
     *
     * @mbg.generated
     */
    private String componentsTemplateUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table components_template
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column components_template.ctid
     *
     * @return the value of components_template.ctid
     *
     * @mbg.generated
     */
    public String getCtid() {
        return ctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column components_template.ctid
     *
     * @param ctid the value for components_template.ctid
     *
     * @mbg.generated
     */
    public void setCtid(String ctid) {
        this.ctid = ctid == null ? null : ctid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column components_template.ctyid
     *
     * @return the value of components_template.ctyid
     *
     * @mbg.generated
     */
    public String getCtyid() {
        return ctyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column components_template.ctyid
     *
     * @param ctyid the value for components_template.ctyid
     *
     * @mbg.generated
     */
    public void setCtyid(String ctyid) {
        this.ctyid = ctyid == null ? null : ctyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column components_template.components_template_name
     *
     * @return the value of components_template.components_template_name
     *
     * @mbg.generated
     */
    public String getComponentsTemplateName() {
        return componentsTemplateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column components_template.components_template_name
     *
     * @param componentsTemplateName the value for components_template.components_template_name
     *
     * @mbg.generated
     */
    public void setComponentsTemplateName(String componentsTemplateName) {
        this.componentsTemplateName = componentsTemplateName == null ? null : componentsTemplateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column components_template.components_template_person
     *
     * @return the value of components_template.components_template_person
     *
     * @mbg.generated
     */
    public String getComponentsTemplatePerson() {
        return componentsTemplatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column components_template.components_template_person
     *
     * @param componentsTemplatePerson the value for components_template.components_template_person
     *
     * @mbg.generated
     */
    public void setComponentsTemplatePerson(String componentsTemplatePerson) {
        this.componentsTemplatePerson = componentsTemplatePerson == null ? null : componentsTemplatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column components_template.components_template_url
     *
     * @return the value of components_template.components_template_url
     *
     * @mbg.generated
     */
    public String getComponentsTemplateUrl() {
        return componentsTemplateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column components_template.components_template_url
     *
     * @param componentsTemplateUrl the value for components_template.components_template_url
     *
     * @mbg.generated
     */
    public void setComponentsTemplateUrl(String componentsTemplateUrl) {
        this.componentsTemplateUrl = componentsTemplateUrl == null ? null : componentsTemplateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table components_template
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ctid=").append(ctid);
        sb.append(", ctyid=").append(ctyid);
        sb.append(", componentsTemplateName=").append(componentsTemplateName);
        sb.append(", componentsTemplatePerson=").append(componentsTemplatePerson);
        sb.append(", componentsTemplateUrl=").append(componentsTemplateUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}